/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsOrdersRouteImport } from './routes/settings/orders'
import { Route as LearnCourseIdRouteImport } from './routes/learn/$courseId'
import { Route as InstructorPayoutsRouteImport } from './routes/instructor/payouts'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor/analytics'
import { Route as InstructorCourseIdRouteImport } from './routes/instructor/$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as CertificatesCompetencyProfileRouteImport } from './routes/certificates/competency-profile'
import { Route as AdminAiSettingsRouteImport } from './routes/admin/ai-settings'
import { Route as VerifyBadgeBadgeCodeRouteImport } from './routes/verify/badge/$badgeCode'
import { Route as LearnCourseIdDiagnosticRouteImport } from './routes/learn/$courseId/diagnostic'
import { Route as LearnCourseIdCompetenciesRouteImport } from './routes/learn/$courseId/competencies'
import { Route as InstructorCourseIdGradingRouteImport } from './routes/instructor/$courseId/grading'
import { Route as LearnCourseIdCompetencyIdProjectRouteImport } from './routes/learn/$courseId/$competencyId/project'
import { Route as LearnCourseIdCompetencyIdAssessmentRouteImport } from './routes/learn/$courseId/$competencyId/assessment'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'
import { Route as ApiAiHintsGenerateRouteImport } from './routes/api/ai/hints/generate'
import { Route as ApiAiFeedbackGenerateRouteImport } from './routes/api/ai/feedback/generate'
import { Route as ApiAiCourseIntelligenceExtractRouteImport } from './routes/api/ai/course-intelligence/extract'
import { Route as ApiAiConfigTestRouteImport } from './routes/api/ai/config/test'
import { Route as ApiAiConfigSetRouteImport } from './routes/api/ai/config/set'
import { Route as ApiAiConfigListRouteImport } from './routes/api/ai/config/list'
import { Route as ApiAiAssessmentsGenerateRouteImport } from './routes/api/ai/assessments/generate'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrdersRoute = SettingsOrdersRouteImport.update({
  id: '/settings/orders',
  path: '/settings/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorPayoutsRoute = InstructorPayoutsRouteImport.update({
  id: '/instructor/payouts',
  path: '/instructor/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCourseIdRoute = InstructorCourseIdRouteImport.update({
  id: '/instructor/$courseId',
  path: '/instructor/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCompetencyProfileRoute =
  CertificatesCompetencyProfileRouteImport.update({
    id: '/competency-profile',
    path: '/competency-profile',
    getParentRoute: () => CertificatesRoute,
  } as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyBadgeBadgeCodeRoute = VerifyBadgeBadgeCodeRouteImport.update({
  id: '/verify/badge/$badgeCode',
  path: '/verify/badge/$badgeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdDiagnosticRoute = LearnCourseIdDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => LearnCourseIdRoute,
} as any)
const LearnCourseIdCompetenciesRoute =
  LearnCourseIdCompetenciesRouteImport.update({
    id: '/competencies',
    path: '/competencies',
    getParentRoute: () => LearnCourseIdRoute,
  } as any)
const InstructorCourseIdGradingRoute =
  InstructorCourseIdGradingRouteImport.update({
    id: '/grading',
    path: '/grading',
    getParentRoute: () => InstructorCourseIdRoute,
  } as any)
const LearnCourseIdCompetencyIdProjectRoute =
  LearnCourseIdCompetencyIdProjectRouteImport.update({
    id: '/$competencyId/project',
    path: '/$competencyId/project',
    getParentRoute: () => LearnCourseIdRoute,
  } as any)
const LearnCourseIdCompetencyIdAssessmentRoute =
  LearnCourseIdCompetencyIdAssessmentRouteImport.update({
    id: '/$competencyId/assessment',
    path: '/$competencyId/assessment',
    getParentRoute: () => LearnCourseIdRoute,
  } as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiHintsGenerateRoute = ApiAiHintsGenerateRouteImport.update({
  id: '/api/ai/hints/generate',
  path: '/api/ai/hints/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFeedbackGenerateRoute = ApiAiFeedbackGenerateRouteImport.update({
  id: '/api/ai/feedback/generate',
  path: '/api/ai/feedback/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCourseIntelligenceExtractRoute =
  ApiAiCourseIntelligenceExtractRouteImport.update({
    id: '/api/ai/course-intelligence/extract',
    path: '/api/ai/course-intelligence/extract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiConfigTestRoute = ApiAiConfigTestRouteImport.update({
  id: '/api/ai/config/test',
  path: '/api/ai/config/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigSetRoute = ApiAiConfigSetRouteImport.update({
  id: '/api/ai/config/set',
  path: '/api/ai/config/set',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigListRoute = ApiAiConfigListRouteImport.update({
  id: '/api/ai/config/list',
  path: '/api/ai/config/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssessmentsGenerateRoute =
  ApiAiAssessmentsGenerateRouteImport.update({
    id: '/api/ai/assessments/generate',
    path: '/api/ai/assessments/generate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/certificates/competency-profile': typeof CertificatesCompetencyProfileRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRouteWithChildren
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/instructor/$courseId/grading': typeof InstructorCourseIdGradingRoute
  '/learn/$courseId/competencies': typeof LearnCourseIdCompetenciesRoute
  '/learn/$courseId/diagnostic': typeof LearnCourseIdDiagnosticRoute
  '/verify/badge/$badgeCode': typeof VerifyBadgeBadgeCodeRoute
  '/api/ai/assessments/generate': typeof ApiAiAssessmentsGenerateRoute
  '/api/ai/config/list': typeof ApiAiConfigListRoute
  '/api/ai/config/set': typeof ApiAiConfigSetRoute
  '/api/ai/config/test': typeof ApiAiConfigTestRoute
  '/api/ai/course-intelligence/extract': typeof ApiAiCourseIntelligenceExtractRoute
  '/api/ai/feedback/generate': typeof ApiAiFeedbackGenerateRoute
  '/api/ai/hints/generate': typeof ApiAiHintsGenerateRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/learn/$courseId/$competencyId/assessment': typeof LearnCourseIdCompetencyIdAssessmentRoute
  '/learn/$courseId/$competencyId/project': typeof LearnCourseIdCompetencyIdProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/certificates/competency-profile': typeof CertificatesCompetencyProfileRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRouteWithChildren
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/learn': typeof LearnIndexRoute
  '/instructor/$courseId/grading': typeof InstructorCourseIdGradingRoute
  '/learn/$courseId/competencies': typeof LearnCourseIdCompetenciesRoute
  '/learn/$courseId/diagnostic': typeof LearnCourseIdDiagnosticRoute
  '/verify/badge/$badgeCode': typeof VerifyBadgeBadgeCodeRoute
  '/api/ai/assessments/generate': typeof ApiAiAssessmentsGenerateRoute
  '/api/ai/config/list': typeof ApiAiConfigListRoute
  '/api/ai/config/set': typeof ApiAiConfigSetRoute
  '/api/ai/config/test': typeof ApiAiConfigTestRoute
  '/api/ai/course-intelligence/extract': typeof ApiAiCourseIntelligenceExtractRoute
  '/api/ai/feedback/generate': typeof ApiAiFeedbackGenerateRoute
  '/api/ai/hints/generate': typeof ApiAiHintsGenerateRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/learn/$courseId/$competencyId/assessment': typeof LearnCourseIdCompetencyIdAssessmentRoute
  '/learn/$courseId/$competencyId/project': typeof LearnCourseIdCompetencyIdProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/certificates/competency-profile': typeof CertificatesCompetencyProfileRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRouteWithChildren
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/instructor/$courseId/grading': typeof InstructorCourseIdGradingRoute
  '/learn/$courseId/competencies': typeof LearnCourseIdCompetenciesRoute
  '/learn/$courseId/diagnostic': typeof LearnCourseIdDiagnosticRoute
  '/verify/badge/$badgeCode': typeof VerifyBadgeBadgeCodeRoute
  '/api/ai/assessments/generate': typeof ApiAiAssessmentsGenerateRoute
  '/api/ai/config/list': typeof ApiAiConfigListRoute
  '/api/ai/config/set': typeof ApiAiConfigSetRoute
  '/api/ai/config/test': typeof ApiAiConfigTestRoute
  '/api/ai/course-intelligence/extract': typeof ApiAiCourseIntelligenceExtractRoute
  '/api/ai/feedback/generate': typeof ApiAiFeedbackGenerateRoute
  '/api/ai/hints/generate': typeof ApiAiHintsGenerateRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/learn/$courseId/$competencyId/assessment': typeof LearnCourseIdCompetencyIdAssessmentRoute
  '/learn/$courseId/$competencyId/project': typeof LearnCourseIdCompetencyIdProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/admin/ai-settings'
    | '/certificates/competency-profile'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses/'
    | '/instructor/'
    | '/learn/'
    | '/instructor/$courseId/grading'
    | '/learn/$courseId/competencies'
    | '/learn/$courseId/diagnostic'
    | '/verify/badge/$badgeCode'
    | '/api/ai/assessments/generate'
    | '/api/ai/config/list'
    | '/api/ai/config/set'
    | '/api/ai/config/test'
    | '/api/ai/course-intelligence/extract'
    | '/api/ai/feedback/generate'
    | '/api/ai/hints/generate'
    | '/api/public/mpesa/callback'
    | '/learn/$courseId/$competencyId/assessment'
    | '/learn/$courseId/$competencyId/project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/admin/ai-settings'
    | '/certificates/competency-profile'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses'
    | '/instructor'
    | '/learn'
    | '/instructor/$courseId/grading'
    | '/learn/$courseId/competencies'
    | '/learn/$courseId/diagnostic'
    | '/verify/badge/$badgeCode'
    | '/api/ai/assessments/generate'
    | '/api/ai/config/list'
    | '/api/ai/config/set'
    | '/api/ai/config/test'
    | '/api/ai/course-intelligence/extract'
    | '/api/ai/feedback/generate'
    | '/api/ai/hints/generate'
    | '/api/public/mpesa/callback'
    | '/learn/$courseId/$competencyId/assessment'
    | '/learn/$courseId/$competencyId/project'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/admin/ai-settings'
    | '/certificates/competency-profile'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses/'
    | '/instructor/'
    | '/learn/'
    | '/instructor/$courseId/grading'
    | '/learn/$courseId/competencies'
    | '/learn/$courseId/diagnostic'
    | '/verify/badge/$badgeCode'
    | '/api/ai/assessments/generate'
    | '/api/ai/config/list'
    | '/api/ai/config/set'
    | '/api/ai/config/test'
    | '/api/ai/course-intelligence/extract'
    | '/api/ai/feedback/generate'
    | '/api/ai/hints/generate'
    | '/api/public/mpesa/callback'
    | '/learn/$courseId/$competencyId/assessment'
    | '/learn/$courseId/$competencyId/project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ScreeningRoute: typeof ScreeningRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachRoute: typeof TeachRoute
  WishlistRoute: typeof WishlistRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  InstructorCourseIdRoute: typeof InstructorCourseIdRouteWithChildren
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorPayoutsRoute: typeof InstructorPayoutsRoute
  LearnCourseIdRoute: typeof LearnCourseIdRouteWithChildren
  SettingsOrdersRoute: typeof SettingsOrdersRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  UUsernameRoute: typeof UUsernameRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  VerifyBadgeBadgeCodeRoute: typeof VerifyBadgeBadgeCodeRoute
  ApiAiAssessmentsGenerateRoute: typeof ApiAiAssessmentsGenerateRoute
  ApiAiConfigListRoute: typeof ApiAiConfigListRoute
  ApiAiConfigSetRoute: typeof ApiAiConfigSetRoute
  ApiAiConfigTestRoute: typeof ApiAiConfigTestRoute
  ApiAiCourseIntelligenceExtractRoute: typeof ApiAiCourseIntelligenceExtractRoute
  ApiAiFeedbackGenerateRoute: typeof ApiAiFeedbackGenerateRoute
  ApiAiHintsGenerateRoute: typeof ApiAiHintsGenerateRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/orders': {
      id: '/settings/orders'
      path: '/settings/orders'
      fullPath: '/settings/orders'
      preLoaderRoute: typeof SettingsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/payouts': {
      id: '/instructor/payouts'
      path: '/instructor/payouts'
      fullPath: '/instructor/payouts'
      preLoaderRoute: typeof InstructorPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/$courseId': {
      id: '/instructor/$courseId'
      path: '/instructor/$courseId'
      fullPath: '/instructor/$courseId'
      preLoaderRoute: typeof InstructorCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/competency-profile': {
      id: '/certificates/competency-profile'
      path: '/competency-profile'
      fullPath: '/certificates/competency-profile'
      preLoaderRoute: typeof CertificatesCompetencyProfileRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/badge/$badgeCode': {
      id: '/verify/badge/$badgeCode'
      path: '/verify/badge/$badgeCode'
      fullPath: '/verify/badge/$badgeCode'
      preLoaderRoute: typeof VerifyBadgeBadgeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId/diagnostic': {
      id: '/learn/$courseId/diagnostic'
      path: '/diagnostic'
      fullPath: '/learn/$courseId/diagnostic'
      preLoaderRoute: typeof LearnCourseIdDiagnosticRouteImport
      parentRoute: typeof LearnCourseIdRoute
    }
    '/learn/$courseId/competencies': {
      id: '/learn/$courseId/competencies'
      path: '/competencies'
      fullPath: '/learn/$courseId/competencies'
      preLoaderRoute: typeof LearnCourseIdCompetenciesRouteImport
      parentRoute: typeof LearnCourseIdRoute
    }
    '/instructor/$courseId/grading': {
      id: '/instructor/$courseId/grading'
      path: '/grading'
      fullPath: '/instructor/$courseId/grading'
      preLoaderRoute: typeof InstructorCourseIdGradingRouteImport
      parentRoute: typeof InstructorCourseIdRoute
    }
    '/learn/$courseId/$competencyId/project': {
      id: '/learn/$courseId/$competencyId/project'
      path: '/$competencyId/project'
      fullPath: '/learn/$courseId/$competencyId/project'
      preLoaderRoute: typeof LearnCourseIdCompetencyIdProjectRouteImport
      parentRoute: typeof LearnCourseIdRoute
    }
    '/learn/$courseId/$competencyId/assessment': {
      id: '/learn/$courseId/$competencyId/assessment'
      path: '/$competencyId/assessment'
      fullPath: '/learn/$courseId/$competencyId/assessment'
      preLoaderRoute: typeof LearnCourseIdCompetencyIdAssessmentRouteImport
      parentRoute: typeof LearnCourseIdRoute
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/hints/generate': {
      id: '/api/ai/hints/generate'
      path: '/api/ai/hints/generate'
      fullPath: '/api/ai/hints/generate'
      preLoaderRoute: typeof ApiAiHintsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/feedback/generate': {
      id: '/api/ai/feedback/generate'
      path: '/api/ai/feedback/generate'
      fullPath: '/api/ai/feedback/generate'
      preLoaderRoute: typeof ApiAiFeedbackGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/course-intelligence/extract': {
      id: '/api/ai/course-intelligence/extract'
      path: '/api/ai/course-intelligence/extract'
      fullPath: '/api/ai/course-intelligence/extract'
      preLoaderRoute: typeof ApiAiCourseIntelligenceExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config/test': {
      id: '/api/ai/config/test'
      path: '/api/ai/config/test'
      fullPath: '/api/ai/config/test'
      preLoaderRoute: typeof ApiAiConfigTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config/set': {
      id: '/api/ai/config/set'
      path: '/api/ai/config/set'
      fullPath: '/api/ai/config/set'
      preLoaderRoute: typeof ApiAiConfigSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config/list': {
      id: '/api/ai/config/list'
      path: '/api/ai/config/list'
      fullPath: '/api/ai/config/list'
      preLoaderRoute: typeof ApiAiConfigListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assessments/generate': {
      id: '/api/ai/assessments/generate'
      path: '/api/ai/assessments/generate'
      fullPath: '/api/ai/assessments/generate'
      preLoaderRoute: typeof ApiAiAssessmentsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiSettingsRoute: AdminAiSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CertificatesRouteChildren {
  CertificatesCompetencyProfileRoute: typeof CertificatesCompetencyProfileRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesCompetencyProfileRoute: CertificatesCompetencyProfileRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface InstructorCourseIdRouteChildren {
  InstructorCourseIdGradingRoute: typeof InstructorCourseIdGradingRoute
}

const InstructorCourseIdRouteChildren: InstructorCourseIdRouteChildren = {
  InstructorCourseIdGradingRoute: InstructorCourseIdGradingRoute,
}

const InstructorCourseIdRouteWithChildren =
  InstructorCourseIdRoute._addFileChildren(InstructorCourseIdRouteChildren)

interface LearnCourseIdRouteChildren {
  LearnCourseIdCompetenciesRoute: typeof LearnCourseIdCompetenciesRoute
  LearnCourseIdDiagnosticRoute: typeof LearnCourseIdDiagnosticRoute
  LearnCourseIdCompetencyIdAssessmentRoute: typeof LearnCourseIdCompetencyIdAssessmentRoute
  LearnCourseIdCompetencyIdProjectRoute: typeof LearnCourseIdCompetencyIdProjectRoute
}

const LearnCourseIdRouteChildren: LearnCourseIdRouteChildren = {
  LearnCourseIdCompetenciesRoute: LearnCourseIdCompetenciesRoute,
  LearnCourseIdDiagnosticRoute: LearnCourseIdDiagnosticRoute,
  LearnCourseIdCompetencyIdAssessmentRoute:
    LearnCourseIdCompetencyIdAssessmentRoute,
  LearnCourseIdCompetencyIdProjectRoute: LearnCourseIdCompetencyIdProjectRoute,
}

const LearnCourseIdRouteWithChildren = LearnCourseIdRoute._addFileChildren(
  LearnCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ScreeningRoute: ScreeningRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachRoute: TeachRoute,
  WishlistRoute: WishlistRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  InstructorCourseIdRoute: InstructorCourseIdRouteWithChildren,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorPayoutsRoute: InstructorPayoutsRoute,
  LearnCourseIdRoute: LearnCourseIdRouteWithChildren,
  SettingsOrdersRoute: SettingsOrdersRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  UUsernameRoute: UUsernameRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  VerifyBadgeBadgeCodeRoute: VerifyBadgeBadgeCodeRoute,
  ApiAiAssessmentsGenerateRoute: ApiAiAssessmentsGenerateRoute,
  ApiAiConfigListRoute: ApiAiConfigListRoute,
  ApiAiConfigSetRoute: ApiAiConfigSetRoute,
  ApiAiConfigTestRoute: ApiAiConfigTestRoute,
  ApiAiCourseIntelligenceExtractRoute: ApiAiCourseIntelligenceExtractRoute,
  ApiAiFeedbackGenerateRoute: ApiAiFeedbackGenerateRoute,
  ApiAiHintsGenerateRoute: ApiAiHintsGenerateRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
