/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsOrdersRouteImport } from './routes/settings/orders'
import { Route as LearnCourseIdRouteImport } from './routes/learn/$courseId'
import { Route as InstructorPayoutsRouteImport } from './routes/instructor/payouts'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor/analytics'
import { Route as InstructorCourseIdRouteImport } from './routes/instructor/$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrdersRoute = SettingsOrdersRouteImport.update({
  id: '/settings/orders',
  path: '/settings/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorPayoutsRoute = InstructorPayoutsRouteImport.update({
  id: '/instructor/payouts',
  path: '/instructor/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCourseIdRoute = InstructorCourseIdRouteImport.update({
  id: '/instructor/$courseId',
  path: '/instructor/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/learn': typeof LearnIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/onboarding': typeof OnboardingRoute
  '/screening': typeof ScreeningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/wishlist': typeof WishlistRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/payouts': typeof InstructorPayoutsRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses/'
    | '/instructor/'
    | '/learn/'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses'
    | '/instructor'
    | '/learn'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/certificates'
    | '/onboarding'
    | '/screening'
    | '/sitemap.xml'
    | '/teach'
    | '/wishlist'
    | '/courses/$courseId'
    | '/instructor/$courseId'
    | '/instructor/analytics'
    | '/instructor/payouts'
    | '/learn/$courseId'
    | '/settings/orders'
    | '/settings/profile'
    | '/u/$username'
    | '/verify/$code'
    | '/courses/'
    | '/instructor/'
    | '/learn/'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CertificatesRoute: typeof CertificatesRoute
  OnboardingRoute: typeof OnboardingRoute
  ScreeningRoute: typeof ScreeningRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachRoute: typeof TeachRoute
  WishlistRoute: typeof WishlistRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  InstructorCourseIdRoute: typeof InstructorCourseIdRoute
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorPayoutsRoute: typeof InstructorPayoutsRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  SettingsOrdersRoute: typeof SettingsOrdersRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  UUsernameRoute: typeof UUsernameRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/orders': {
      id: '/settings/orders'
      path: '/settings/orders'
      fullPath: '/settings/orders'
      preLoaderRoute: typeof SettingsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/payouts': {
      id: '/instructor/payouts'
      path: '/instructor/payouts'
      fullPath: '/instructor/payouts'
      preLoaderRoute: typeof InstructorPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/$courseId': {
      id: '/instructor/$courseId'
      path: '/instructor/$courseId'
      fullPath: '/instructor/$courseId'
      preLoaderRoute: typeof InstructorCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CertificatesRoute: CertificatesRoute,
  OnboardingRoute: OnboardingRoute,
  ScreeningRoute: ScreeningRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachRoute: TeachRoute,
  WishlistRoute: WishlistRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  InstructorCourseIdRoute: InstructorCourseIdRoute,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorPayoutsRoute: InstructorPayoutsRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  SettingsOrdersRoute: SettingsOrdersRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  UUsernameRoute: UUsernameRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
